---

- name: Install packages and configure the media server...
  hosts: media_server
  become: true
  gather_facts: false

  tasks:

    - name: Become assertions...
      tags:
        - always
      ansible.builtin.include_role:
        name: assert
        tasks_from: become.yml

    - name: Including install tasks from media_server role...
      ansible.builtin.include_role:
        name: media_server
        tasks_from: install.yml

...
